local HeightMonitor = require("controller/HeightMonitor")

describe("HeightMonitor #flight", function()
    it("Can detect direction change", function()
        local h = HeightMonitor.New()
        h.Enable()
        assert.False(h.Track(1))
        assert.False(h.Track(1))
        assert.False(h.Track(1))
        assert.False(h.Track(0))
        assert.True(h.Track(1))

        h.Enable()
        assert.False(h.Track(0))
        assert.False(h.Track(1))
        assert.False(h.Track(2))
        assert.True(h.Track(1))

        h.Enable()
        assert.False(h.Track(4))
        assert.False(h.Track(3))
        assert.False(h.Track(2))
        assert.True(h.Track(3))

        h.Enable()
        assert.False(h.Track(0))
        assert.False(h.Track(0))
        assert.False(h.Track(0))
        assert.False(h.Track(0))
        assert.False(h.Track(0))
    end)
end)
