-- ################################################################################
-- #                  Copyright 2014-2022 Novaquark SAS                           #
-- ################################################################################

-----------------------------------------------------------------------------------
-- Atlas
--
-- The atlas provide a stellar atlas providing all informations about stellar
-- bodies of the universe.
-----------------------------------------------------------------------------------

return {
    [0] = {
      [1] = {
        id = 1,
        name = { "Madis", "Madis", "Madis"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Barren", "Stérile", "Ödnis"},
        classification = { "Hyperthermoplanet", "Hyperthermoplanète", "Hyperthermoplanet"},
        habitability = { "Low", "Faible", "Gering"},
        description = {
          [[Madis is a barren wasteland of a rock, it sits closest to the sun and temperatures reach extreme highs during the day. The Arkship geological survey reports long rocky valleys intermittently separated by small ravines.]],
          [[Madis est un désert rocheux stérile, elle est située au plus près du soleil et les températures atteignent des sommets extrêmes pendant la journée. L'étude géologique de l'Arche fait état de longues vallées rocheuses séparées par intermittence par de petits ravins.]],
          [[Madis ist eine karge Felswüste, welche der Sonne am nächsten liegt und deren Temperaturen tagsüber extreme Werte erreichen. Die geologische Untersuchung des Archenschiffes berichtet von langen felsigen Tälern, die von kleinen Schluchten unterbrochen werden.]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/madis.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = true,
        systemId = 0,
        positionInSystem = 1,
        satellites = { 10, 11, 12},
        center = { 17465536.00, 22665536.00, -34464.00 },
        gravity = 3.5325,
        radius = 44300.00,
        atmosphereThickness = 6200.00,
        atmosphereRadius = 50700.00,
        surfaceArea = 24661377024,
        surfaceAverageAltitude = 750,
        surfaceMaxAltitude = 850,
        surfaceMinAltitude = 670,
        GM = 6932495925.00,
        ores = {
          {"Hematite","Hématite","Hämatit"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Quartz","Quartz","Quarz"},
          {"Coal","Charbon","Kohle"},
          {"Natron","Natron","Soda"},
          {"Garnierite","Garniérite","Garnierit"}
        },
        territories = 30722
      },
      [10] = {
        id = 10,
        name = {"Madis Moon 1","Madis Lune 1","Madis Mond 1"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = true,
        systemId = 1,
        positionInSystem = 1,
        satellites = nil,
        center = { 17448118.86, 22966848.03, 143079.98 },
        gravity = 0.7850,
        radius = 10000.00,
        atmosphereThickness = 0.00,
        atmosphereRadius = 10000.00,
        GM = 78500000.00,
        surfaceArea = 1256637056,
        surfaceAverageAltitude = 210,
        surfaceMaxAltitude = 420,
        surfaceMinAltitude = 0,
        ores = {
          {"Coal","Charbon","Kohle"},
          {"Hematite","Hématite","Hämatit"},
          {"Limestone","Calcaire","Kalkstein"},
          {"Vanadinite","Vanadinite","Vanadinit"}
        },
        territories = 1472
      },
      [11] = {
        id = 11,
        name = {"Madis Moon 2","Madis Lune 2","Madis Mond 2"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = true,
        systemId = 1,
        positionInSystem = 2,
        satellites = nil,
        center = { 17194626.00, 22243633.88, -214962.81 },
        gravity = 0.9420,
        radius = 12000.00,
        atmosphereThickness = 0.00,
        atmosphereRadius = 12000.00,
        GM = 135648000.00,
        surfaceArea = 1809557376,
        surfaceAverageAltitude = -700,
        surfaceMaxAltitude = 300,
        surfaceMinAltitude = -2900,
        ores = {
          {"Hematite","Hématite","Hämatit"},
          {"Quartz","Quartz","Quarz"},
          {"Malachite","Malachite","Malachit"},
          {"Ilmenite","Ilménite","Ilmenit"}
        },
        territories = 1922
      },
      [12] = {
        id = 12,
        name = {"Madis Moon 3","Madis Lune 3","Madis Mond 3"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = true,
        systemId = 1,
        positionInSystem = 3,
        satellites = nil,
        center = { 17520617.44, 22184726.90, -309986.22 },
        gravity = 1.1775,
        radius = 15000.00,
        atmosphereThickness = 00,
        atmosphereRadius = 15000.00,
        GM = 264937500.00,
        surfaceArea = 2827433472,
        surfaceAverageAltitude = 700,
        surfaceMaxAltitude = 1100,
        surfaceMinAltitude = 0,
        ores = {
          {"Quartz","Quartz","Quarz"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Natron","Natron","Soda"},
          {"Columbite","Columbite","Columbit"}
        },
        territories = 3632
      },
      [2] = {
        id = 2,
        name = { "Alioth", "Alioth", "Alioth"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Forest", "Forêt", "Wald"},
        classification = { "Mesoplanet", "Mésoplanète", "Mesoplanet"},
        habitability = { "High", "Elevée", "Hohe"},
        description = {
          [[Alioth is the planet selected by the Arkship for landfall, it is a typical goldilocks planet where humanity may rebuild in the coming decades. The Arkship geological survey reports mountainous regions alongside deep seas and lush forests. This is where it all starts.]],
          [[Alioth est la planète sélectionnée par l'Arche pour l'atterrissage, c'est une planète "Boucles d'or" typique où l'humanité peut se reconstruire dans les prochaines décennies. L'étude géologique de l'Arche fait état de régions montagneuses côtoyant des mers profondes et des forêts luxuriantes. C'est ici que tout commence]],
          [[Alioth ist jener Planet, den das Archenschiff für die Landung ausgewählt hat, ein typischer Goldlöckchen-Planet, auf welchem sich die Menschheit in den kommenden Jahrzehnten wieder aufbauen kann. Die geologische Untersuchung des Archenschiffs berichtet von bergigen Regionen neben tiefen Meeren und üppigen Wäldern. Hier fängt alles an.]],
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/alioth.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = true,
        systemId = 0,
        positionInSystem = 2,
        satellites = { 21, 22, 26},
        center = { -8.00, -8.00, -126303.00 },
        gravity = 9.8910,
        radius = 126067.90,
        atmosphereThickness = 4960.00,
        atmosphereRadius = 131020.00,
        surfaceArea = 199718780928,
        surfaceAverageAltitude = 200,
        surfaceMaxAltitude = 1100,
        surfaceMinAltitude = -330,
        GM = 157198800627.69,
        ores = {
          {"Coal","Charbon","Kohle"},
          {"Quartz","Quartz","Quarz"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Hematite","Hématite","Hämatit"},
          {"Acanthite","Acanthite","Akanthit"},
          {"Malachite","Malachite","Malachit"}
        },
        territories = 259472
      },
      [21] = {
        id = 21,
        name = {"Alioth Moon 1","Alioth Lune 1","Alioth Mond 1"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/alioth_moon1.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = true,
        systemId = 2,
        positionInSystem = 2,
        satellites = nil,
        center = { 457932.99, -1509009.24, 115525.00 },
        gravity = 2.3550,
        radius = 30000.00,
        atmosphereThickness = 0.00,
        atmosphereRadius = 30000.00,
        GM = 2119500000.00,
        surfaceArea = 11309733888,
        surfaceAverageAltitude = 140,
        surfaceMaxAltitude = 200,
        surfaceMinAltitude = 10,
        ores = {
          {"Coal","Charbon","Kohle"},
          {"Quartz","Quartz","Quarz"},
          {"Chromite","Chromite","Chromit"}
        },
        territories = 14522
      },
      [22] = {
        id = 22,
        name = {"Alioth Moon 4","Alioth Lune 4","Alioth Mond 4"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/alioth_moon4.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = true,
        systemId = 2,
        positionInSystem = 3,
        satellites = nil,
        center = { -1692694.85, 729681.81, -411465.62 },
        gravity = 2.3809,
        radius = 30330.00,
        atmosphereThickness = 0.00,
        atmosphereRadius = 30330.00,
        GM = 2190215699.55,
        surfaceArea = 11559916544,
        surfaceAverageAltitude = -15,
        surfaceMaxAltitude = -5,
        surfaceMinAltitude = -50,
        ores = {
          {"Bauxite","Bauxite","Bauxit"},
          {"Hematite","Hématite","Hämatit"},
          {"Limestone","Calcaire","Kalkstein"}
        },
        territories = 14522
      },
      [26] = {
        id = 26,
        name = { "Sanctuary", "Sanctuary", "Sanctuary"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = { "Forest", "Forêt", "Wald"},
        classification = { "Mesoplanet", "Mésoplanète", "Mesoplanet"},
        habitability = { "High", "Elevée", "Hohe"},
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/sanctuary_moon.png",
        hasAtmosphere = true,
        isSanctuary = true,
        isInSafeZone = true,
        systemId = 2,
        positionInSystem = 1,
        satellites = nil,
        center = { -1404834.53, 562655.32, -285074.95 },
        gravity = 9.8100,
        radius = 83400.00,
        atmosphereThickness = 6200.00,
        atmosphereRadius = 89550.00,
        GM = 68234043600.00,
        surfaceArea = 87406149632,
        surfaceAverageAltitude = 80,
        surfaceMaxAltitude = 500,
        surfaceMinAltitude = -60,
        ores = {
          {"Quartz","Quartz","Quarz"},
          {"Coal","Charbon","Kohle"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Hematite","Hématite","Hämatit"}
        },
        territories = 111632
      },
      [3] = {
        id = 3,
        name = { "Thades", "Thades", "Thades"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Desert", "Désert", "Wüste"},
        classification = { "Thermoplanet", "Thermoplanète", "Thermoplanet"},
        habitability = { "Low", "Faible", "Gering"},
        description = {
          [["Thades is a scorched desert planet. Perhaps it was once teaming with life but now all that remains is ash and dust. The Arkship geological survey reports a rocky mountainous planet bisected by a massive unnatural ravine, something happened to this planet."]],
          [["Thades est une planète désertique brûlée. Peut-être était-elle autrefois pleine de vie, mais il ne reste plus que des cendres et de la poussière. L'étude géologique de l'Arche rapporte une planète montagneuse et rocheuse coupée en deux par un ravin massif non naturel, quelque chose est arrivé à cette planète."]],
          [["Thades ist ein verbrannter Wüstenplanet. Vielleicht war er einst voller Leben, aber jetzt ist nur noch Asche und Staub übrig. Die geologische Untersuchung des Archenschiffes berichtet von einem felsigen, gebirgigen Planeten, der von einer gewaltigen, unnatürlichen Schlucht durchzogen ist - irgendetwas ist mit diesem Planeten geschehen."]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/thades.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = true,
        systemId = 0,
        positionInSystem = 3,
        satellites = { 30, 31},
        center = { 29165536.00, 10865536.00, 65536.00 },
        gravity = 4.8670,
        radius = 49000.00, 
        atmosphereThickness = 31020.00,
        atmosphereRadius = 80020.00,
        GM = 11685667000.00,
        surfaceArea = 30171856896,
        surfaceAverageAltitude = 13640,
        surfaceMaxAltitude = 13690,
        surfaceMinAltitude = 370,
        ores = {
          {"Quartz","Quartz","Quarz"},
          {"Coal","Charbon","Kohle"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Hematite","Hématite","Hämatit"},
          {"Chromite","Chromite","Chromit"},
          {"Pyrite","Pyrite","Pyrit"}
        },
        territories = 38882
      },
      [30] = {
        id = 30,
        name = {"Thades Moon 1","Thades Lune 1","Thades Mond 1"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = true,
        systemId = 3,
        positionInSystem = 1,
        satellites = nil,
        center = { 29214403.49, 10907080.70, 433861.28 },
        gravity = 1.0990,
        radius = 14000.00,
        atmosphereThickness = 0.00,
        atmosphereRadius = 14000.00,
        GM = 215404000.00,
        surfaceArea = 2463008768,
        surfaceAverageAltitude = 60,
        surfaceMaxAltitude = 300,
        surfaceMinAltitude = 0,
        ores = {
          {"Coal","Charbon","Kohle"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Natron","Natron","Soda"},
          {"Vanadinite","Vanadinite","Vanadinit"}
        },
        territories = 3002
      },
      [31] = {
        id = 31,
        name = {"Thades Moon 2","Thades Lune 2","Thades Mond 2"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = true,
        systemId = 3,
        positionInSystem = 2,
        satellites = nil,
        center ={ 29404194.34, 10432766.60, 19553.82 },
        gravity = 1.1775,
        radius = 15000.00,
        atmosphereThickness = 0.00,
        atmosphereRadius = 15000.00,
        GM = 264937500.00,
        surfaceArea = 2827433472,
        surfaceAverageAltitude = 70,
        surfaceMaxAltitude = 350,
        surfaceMinAltitude = 0,
        ores = {
          {"Bauxite","Bauxite","Bauxit"},
          {"Hematite","Hématite","Hämatit"},
          {"Quartz","Quartz","Quarz"},
          {"Malachite","Malachite","Malachit"},
          {"Ilmenite","Ilménite","Ilmenit"}
        },
        territories = 3632
      },
      [4] = {
        id = 4,
        name = { "Talemai", "Talemai", "Talemai"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Barren", "Stérile", "Öder"},
        classification = { "Psychroplanet", "Psychroplanète", "Psychroplanet"},
        habitability = { "Average", "Moyenne", "Mittlere "},
        description = {
          [[Talemai is a planet in the final stages of an Ice Age. It seems likely that the planet was thrown into tumult by a cataclysmic volcanic event which resulted in its current state. The Arkship geological survey reports large mountainous regions across the entire planet.]],
          [[Talemai est une planète qui se trouve dans les derniers stades d'une ère glaciaire. Il semble probable que la planète ait été projetée dans le tumulte par un événement volcanique cataclysmique qui a abouti à son état actuel. L'étude géologique de l'Arche fait état de grandes régions montagneuses sur l'ensemble de la planète.]],
          [[Talemai ist ein Planet, der sich im Endstadium einer Eiszeit befindet. Es ist wahrscheinlich, dass der Planet durch ein kataklysmisches vulkanisches Ereignis in Aufruhr versetzt wurde, der zu seinem heutigen Zustand führte. Die geologische Untersuchung des Archenschiffes zeigt große Gebirgsregionen überall auf dem Planeten.]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/talemai.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 0,
        positionInSystem = 4,
        satellites = { 40, 41, 42},
        center = { -13234464.00, 55765536.00, 465536.00 },
        gravity = 4.5530,
        radius = 57500.00,
        atmosphereThickness = 8690.00,
        atmosphereRadius = 66090.00,
        GM = 15053356250.00,
        surfaceArea = 41547563008,
        surfaceAverageAltitude = 580,
        surfaceMaxAltitude = 610,
        surfaceMinAltitude = 520,
        ores = {
          {"Bauxite","Bauxite","Bauxit"},
          {"Hematite","Hématite","Hämatit"},
          {"Quartz","Quartz","Quarz"},
          {"Coal","Charbon","Kohle"},
          {"Natron","Natron","Soda"},
          {"Limestone","Calcaire","Kalkstein"},
          {"Petalite","Pétalite","Petalit"}
        },
        territories = 52922
      },
      [40] = {
        id = 40,
        name = {"Talemai Moon 2","Talemai Lune 2","Talemai Mond 2"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 4,
        positionInSystem = 2,
        satellites = nil,
        center = { -13503090.34, 55594324.49, 769836.53 },
        gravity = 0.9420,
        radius = 12000.00,
        atmosphereThickness = 0.00,
        atmosphereRadius = 12000.00,
        GM = 135648000.00,
        surfaceArea = 1809557376,
        surfaceAverageAltitude = 250,
        surfaceMaxAltitude = 450,
        surfaceMinAltitude = 0,
        ores = {
          {"Bauxite","Bauxite","Bauxit"},
          {"Quartz","Quartz","Quarz"},
          {"Coal","Charbon","Kohle"},
          {"Chromite","Chromite","Chromit"},
          {"Columbite","Columbite","Columbit"}
        },
        territories = 1922
      },
      [41] = {
        id = 41,
        name = {"Talemai Moon 3","Talemai Lune 3","Talemai Mond 3"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 4,
        positionInSystem = 3,
        satellites = nil,
        center = { -12800514.62, 55700257.46, 325207.84 },
        gravity = 0.8635,
        radius = 11000.00,
        atmosphereThickness = 0.00,
        atmosphereRadius = 11000.00,
        GM = 104483500.00,
        surfaceArea = 1520530944,
        surfaceAverageAltitude = 190,
        surfaceMaxAltitude = 400,
        surfaceMinAltitude = 0,
        ores = {
          {"Hematite","Hématite","Hämatit"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Coal","Charbon","Kohle"},
          {"Natron","Natron","Soda"},
          {"Rhodonite","Rhodonite","Rhodonit"}
        },
        territories = 1922
      },
      [42] = {
        id = 42,
        name = {"Talemai Moon 1","Talemai Lune 1","Talemai Mond 1"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 4,
        positionInSystem = 1,
        satellites = nil,
        center = { -13058408.39, 55781856.76, 740177.66 },
        gravity = 1.1775,
        radius = 15000.00,
        atmosphereThickness = 0.00,
        atmosphereRadius = 15000.00,
        GM = 264937500.00,
        surfaceArea = 2827433472,
        surfaceAverageAltitude = 720,
        surfaceMaxAltitude = 850,
        surfaceMinAltitude = 0,
        ores = {
          {"Quartz","Quartz","Quarz"},
          {"Coal","Charbon","Kohle"},
          {"Hematite","Hématite","Hämatit"},
          {"Limestone","Calcaire","Kalkstein"},
          {"Vanadinite","Vanadinite","Vanadinit"}
        },
        territories = 3632
      },
      [5] = {
        id = 5,
        name = { "Feli", "Feli", "Feli"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Barren", "Stérile", "Öder"},
        classification = { "Mesoplanet", "Mésoplanète", "Mesoplanet"},
        habitability = { "Low", "Faible", "Gering"},
        description = {
          [[Feli is easily identified by its massive and deep crater. Outside of the crater, the Arkship geological survey reports a fairly bland and uniform planet, it also cannot explain the existence of the crater. Feli is particular for having an extremely small atmosphere, allowing life to develop in the deeper areas of its crater but limiting it drastically on the actual surface.]],
          [[Feli est facilement identifiable par son cratère massif et profond. En dehors du cratère, l'étude géologique de l'Arche révèle une planète assez fade et uniforme, mais ne peut expliquer l'existence du cratère. Feli a la particularité d'avoir une atmosphère extrêmement fine, permettant à la vie de se développer dans les zones profondes de son cratère mais la limitant drastiquement à la surface.]],
          [[Feli ist leicht an seinem massiven und tiefen Krater zu erkennen. Außerhalb des Kraters berichtet die geologische Untersuchung des Archenschiffes von einem ziemlich faden und gleichförmigen Planeten, sie kann auch die Existenz des Kraters nicht erklären. Feli zeichnet sich durch eine extrem geringe Atmosphäre aus, die die Entwicklung von Leben in den tieferen Bereichen des Kraters ermöglicht, es aber auf der Oberfläche drastisch einschränkt]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/feli.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 0,
        positionInSystem = 5,
        satellites = { 50},
        center = { -43534464.00, 22565536.00, -48934464.00 },
        gravity = 4.7100,
        radius = 41800.00,
        atmosphereThickness = 62040.00,
        atmosphereRadius = 103740.00,
        GM = 8229500400.00,
        surfaceArea = 21956466688,
        surfaceAverageAltitude = 18300,
        surfaceMaxAltitude = 18500,
        surfaceMinAltitude = 46,
        ores = {
          {"Coal","Charbon","Kohle"},
          {"Quartz","Quartz","Quarz"},
          {"Malachite","Malachite","Malachit"},
          {"Hematite","Hématite","Hämatit"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Petalite","Pétalite","Petalit"},
          {"Gold nuggets","Pépites d'or","Goldnuggets"}
        },
        territories = 27002
      },
      [50] = {
        id = 50,
        name = {"Feli Moon 1","Feli Lune 1","Feli Mond 1"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 5,
        positionInSystem = 1,
        satellites = nil,
        center = { -43902841.78, 22261034.70, -48862386.00 },
        gravity = 1.0990,
        radius = 14000.00,
        atmosphereThickness = 0,
        atmosphereRadius = 14000.00,
        GM = 215404000.00,
        surfaceArea = 2463008768,
        surfaceAverageAltitude = 800,
        surfaceMaxAltitude = 900,
        surfaceMinAltitude = 0,
        ores = {
          {"Coal","Charbon","Kohle"},
          {"Hematite","Hématite","Hämatit"},
          {"Malachite","Malachite","Malachit"},
          {"Ilmenite","Ilménite","Ilmenit"}
        },
        territories = 3002
      },
      [6] = {
        id = 6,
        name = { "Sicari", "Sicari", "Sicari"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Desert", "Désert", "Wüste"},
        classification = { "Mesoplanet", "Mésoplanète", "Mesoplanet"},
        habitability = { "Average", "Moyenne", "Mittlere "},
        description = {
          [[Sicari is a typical desert planet, it has survived for millenniums and will continue to endure. While not the most habitable of environments it remains a relatively untouched and livable planet of the Alioth sector. The Arkship geological survey reports large flatlands alongside steep plateaus.]],
          [[Sicari est une planète désertique typique, elle a survécu pendant des millénaires et continuera à le faire. Bien qu'elle ne soit pas l'environnement le plus habitable, elle reste une planète relativement intacte et vivable du secteur Alioth. L'étude géologique de l'Arche fait état de vastes plaines côtoyant des plateaux escarpés.]],
          [[Sicari ist ein typischer Wüstenplanet, der seit Jahrtausenden überlebt hat und auch weiterhin überleben wird. Obwohl er nicht die bewohnbarste Umgebung ist, bleibt er ein relativ unberührter und bewohnbarer Planet des Alioth-Sektors. Die geologische Untersuchung des Archenschiffes berichtet von großen Ebenen neben steilen Plateaus.]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/sicari.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 0,
        positionInSystem = 6,
        satellites = nil,
        center = { 52765536.00, 27165536.00, 52065536.00 },
        gravity = 4.0035,
        radius = 51100.00,
        atmosphereThickness = 7450.00,
        atmosphereRadius = 57890.00,
        GM = 10453979235.00,
        surfaceArea = 32813432832,
        surfaceAverageAltitude = 130,
        surfaceMaxAltitude = 220,
        surfaceMinAltitude = 50,
        ores = {
          {"Bauxite","Bauxite","Bauxit"},
          {"Chromite","Chromite","Chromit"},
          {"Coal","Charbon","Kohle"},
          {"Hematite","Hématite","Hämatit"},
          {"Quartz","Quartz","Quarz"},
          {"Pyrite","Pyrite","Pyrit"},
          {"Kolbeckite","Kolbeckite","Kolbeckit"}
        },
        territories = 41072
      },
      [7] = {
        id = 7,
        name = { "Sinnen", "Sinnen", "Sinnen"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Desert", "Désert", "Wüste"},
        classification = { "Mesoplanet", "Mésoplanète", "Mesoplanet"},
        habitability = { "Average", "Moyenne", "Mittlere "},
        description = {
          [[Sinnen is a an empty and rocky hell. With no atmosphere to speak of it is one of the least hospitable planets in the sector. The Arkship geological survey reports mostly flatlands alongside deep ravines which look to have once been riverbeds. This planet simply looks to have dried up and died, likely from solar winds.]],
          [[Sinnen est un enfer vide et rocheux. Sans atmosphère à proprement parler, c'est l'une des planètes les moins hospitalières du secteur. L'étude géologique de l'Arche indique que la plupart des terres sont plates et bordées de profonds ravins qui semblent avoir été des lits de rivière. Cette planète semble simplement s'être asséchée et être morte, probablement à cause des vents solaires.]],
          [[Sinnen ist eine leere und felsige Hölle. Ohne nennenswerte Atmosphäre ist er einer der unwirtlichsten Planeten des Sektors. Die geologische Untersuchung des Archenschiffes ergab, dass es sich größtenteils um flaches Land handelt, das von tiefen Schluchten durchzogen ist, die früher einmal Flussbetten gewesen zu sein scheinen. Dieser Planet scheint einfach ausgetrocknet und gestorben zu sein, wahrscheinlich durch Sonnenwinde.]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/sinnen.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 0,
        positionInSystem = 7,
        satellites = {70},
        center = { 58665536.00, 29665536.00, 58165536.00 },
        gravity = 4.3175,
        radius = 54950.00,
        atmosphereThickness = 9310.00,
        atmosphereRadius = 64110.00,
        GM = 13036702043.75,
        surfaceArea = 37944188928,
        surfaceAverageAltitude = 317,
        surfaceMaxAltitude = 360,
        surfaceMinAltitude = 23,
        ores = {
          {"Limestone","Calcaire","Kalkstein"},
          {"Coal","Charbon","Kohle"},
          {"Hematite","Hématite","Hämatit"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Quartz","Quartz","Quarz"},
          {"Acanthite","Acanthite","Akanthit"},
          {"Cryolite","Cryolite","Kryolith"}
        },
        territories = 48002
      },
      [70] = {
        id = 70,
        name = {"Sinnen Moon 1","Sinnen Lune 1","Sinnen Mond 1"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 7,
        positionInSystem = 1,
        satellites = nil,
        center = { 58969618.12, 29797943.44, 57969448.98 },
        gravity = 1.3345,
        radius = 17000.00,
        atmosphereThickness = 0,
        atmosphereRadius = 17000.00,
        GM = 385670500.00,
        surfaceArea = 3631681280,
        surfaceAverageAltitude = -2050,
        surfaceMaxAltitude = -1950,
        surfaceMinAltitude = -2150,
        ores = {
          {"Quartz","Quartz","Quarz"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Chromite","Chromite","Chromit"},
          {"Columbite","Columbite","Columbit"}
        },
        territories = 4322
      },
      [8] = {
        id = 8,
        name = { "Teoma", "Teoma", "Teoma"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Forest", "Forêt", "Wald"},
        classification = { "Mesoplanet", "Mésoplanète", "Mesoplanet"},
        habitability = { "High", "Elevée", "Hohe"},
        description = {
          [[[REDACTED] The Arkship geological survey [REDACTED]. This planet should not be here.]],
          [[[CENSURÉ] L'enquête géologique de l'Arche [CENSURÉ]. Cette planète ne devrait pas être là.]],
          [[[ZENSIERT] Die geologische Untersuchung von Arkship [ZENSIERT]. Dieser Planet sollte nicht hier sein.]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/teoma.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 0,
        positionInSystem = 8,
        satellites = nil,
        center = { 80865536.00, 54665536.00, -934464.00 },
        gravity = 4.7885,
        radius = 62000.00,
        atmosphereThickness = 4960.00,
        atmosphereRadius = 66960.00,
        GM = 18406994000.00,
        surfaceArea = 48305131520,
        surfaceAverageAltitude = 700,
        surfaceMaxAltitude = 1100,
        surfaceMinAltitude = -200,
        ores = {
          {"Coal","Charbon","Kohle"},
          {"Hematite","Hématite","Hämatit"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Quartz","Quartz","Quarz"},
          {"Natron","Natron","Soda"},
          {"Garnierite","Garniérite","Garnierit"},
          {"Cobaltite","Cobaltite","Cobaltit"}
        },
        territories = 60752
      },
      [9] = {
        id = 9,
        name = { "Jago", "Jago", "Jago"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Water", "Eau", "Wasser"},
        classification = { "Mesoplanet", "Mésoplanète", "Mesoplanet"},
        habitability = { "Very High", "Très élevée", "Sehr hohe"},
        description = {
          [[Jago is a water planet. The large majority of the planet&apos,s surface is covered by large oceans dotted by small areas of landmass across the planet. The Arkship geological survey reports deep seas across the majority of the planet with sub 15 percent coverage of solid ground.]],
          [[Jago est une planète d'eau. La grande majorité de la surface de la planète est couverte de grands océans parsemés de petites zones de masse terrestre. L'étude géologique de l'Arche fait état de mers profondes sur la majorité de la planète et d'une couverture de moins de 15 % de terre ferme.]],
          [[Jago ist ein Wasserplanet. Der größte Teil der Oberfläche des Planeten ist von großen Ozeanen bedeckt, die von kleinen Landmassen über den Planeten verteilt sind. Die geologische Untersuchung des Archenschiffes ergab, dass der größte Teil des Planeten von tiefen Meeren bedeckt ist und weniger als 15 Prozent festen Boden aufweist.]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/jago.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 0,
        positionInSystem = 9,
        satellites = nil,
        center = { -94134464.00, 12765536.00, -3634464.00 },
        gravity = 4.9455,
        radius = 61590.00,
        atmosphereThickness = 8690.00,
        atmosphereRadius = 70190.00,
        GM = 18759904118.55,
        surfaceArea = 47668367360,
        surfaceAverageAltitude = 0,
        surfaceMaxAltitude = 1200,
        surfaceMinAltitude = -500,
        ores = {
          {"Chromite","Chromite","Chromit"},
          {"Quartz","Quartz","Quarz"},
          {"Petalite","Pétalite","Petalit"},
          {"Kolbeckite","Kolbeckite","Kolbeckit"},
          {"Columbite","Columbite","Columbit"}
        },
        territories = 60752
      },
      [100] = {
        id = 100,
        name = { "Lacobus", "Lacobus", "Lacobus"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Ice", "Glace", "Eis"},
        classification = { "Psychroplanet", "Psychroplanète", "Psychroplanet"},
        habitability = { "Average", "Moyenne", "Mittlere "},
        description = {
          [[Lacobus is an ice planet that also features large bodies of water. The Arkship geological survey reports deep oceans alongside a frozen and rough mountainous environment. Lacobus seems to feature regional geothermal activity allowing for the presence of water on the surface.]],
          [[Lacobus est une planète de glace qui présente également de grandes étendues d'eau. L'étude géologique de l'Arche fait état d'océans profonds et d'un environnement montagneux gelé et rugueux. Lacobus semble présenter une activité géothermique régionale permettant la présence d'eau à la surface.]],
          [[Lacobus ist ein Eisplanet, der auch große Wassermassen aufweist. Die geologische Untersuchung des Archenschiffes berichtet von tiefen Ozeanen neben einer gefrorenen und rauen bergigen Umgebung. Lacobus scheint eine regionale geothermische Aktivität aufzuweisen, die das Vorhandensein von Wasser an der Oberfläche ermöglicht.]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/lacobus.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 0,
        positionInSystem = 10,
        satellites = { 101, 102, 103},
        center = { 98865536.00, -13534464.00, -934464.00 },
        gravity = 4.4745,
        radius = 55650.00,
        atmosphereThickness = 9930.00,
        atmosphereRadius = 65530.00,
        GM = 13857179726.25,
        surfaceArea = 38917074944,
        surfaceAverageAltitude = 1480,
        surfaceMaxAltitude = 1660,
        surfaceMinAltitude = 1240,
        ores = {
          {"Natron","Natron","Soda"},
          {"Hematite","Hématite","Hämatit"},
          {"Pyrite","Pyrite","Pyrit"},
          {"Gold nuggets","Pépites d'or","Goldnuggets"},
          {"Ilmenite","Ilménite","Ilmenit"}
        },
        territories = 50432
      },
      [101] = {
        id = 101,
        name = {"Lacobus Moon 3","Lacobus Lune 3","Lacobus Mond 3"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 100,
        positionInSystem = 3,
        satellites = nil,
        center = { 98905290.17, -13950923.06, -647589.28 },
        gravity = 1.1775,
        radius = 15000.00,
        atmosphereThickness = 0,
        atmosphereRadius = 15000.00,
        GM = 264937500.00,
        surfaceArea = 2827433472,
        surfaceAverageAltitude = 500,
        surfaceMaxAltitude = 820,
        surfaceMinAltitude = 3,
        ores = {
          {"Coal","Charbon","Kohle"},
          {"Pyrite","Pyrite","Pyrit"},
          {"Rhodonite","Rhodonite","Rhodonit"}
        },
        territories = 3632
      },
      [102] = {
        id = 102,
        name = {"Lacobus Moon 1","Lacobus Lune 1","Lacobus Mond 1"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 100,
        positionInSystem = 1,
        satellites = nil,
        center = { 99180967.44, -13783860.94, -926156.93 },
        gravity = 1.4130,
        radius = 18000.00,
        atmosphereThickness = 0,
        atmosphereRadius = 18000.00,
        GM = 457812000.00,
        surfaceArea = 4071504128,
        surfaceAverageAltitude = 150,
        surfaceMaxAltitude = 300,
        surfaceMinAltitude = 10,
        ores = {
          {"Hematite","Hématite","Hämatit"},
          {"Acanthite","Acanthite","Akanthit"},
          {"Vanadinite","Vanadinite","Vanadinit"}
        },
        territories = 5072
      },
      [103] = {
        id = 103,
        name = {"Lacobus Moon 2","Lacobus Lune 2","Lacobus Mond 2"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 100,
        positionInSystem = 2,
        satellites = nil,
        center = { 99250054.22, -13629215.27, -1059341.74 },
        gravity = 1.0990,
        radius = 14000.00,
        atmosphereThickness = 0,
        atmosphereRadius = 14000.00,
        GM = 215404000.00,
        surfaceArea = 2463008768,
        surfaceAverageAltitude = -1380,
        surfaceMaxAltitude = -1280,
        surfaceMinAltitude = -1880,
        ores = {
          {"Quartz","Quartz","Quarz"},
          {"Limestone","Calcaire","Kalkstein"},
          {"Petalite","Pétalite","Petalit"},
          {"Ilmenite","Ilménite","Ilmenit"}
        },
        territories = 3002
      },
      [110] = {
        id = 110,
        name = { "Symeon", "Symeon", "Symeon"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Ice, Desert", "Glace, Désert", "Eis, Wüste"},
        classification = { "Hybrid", "Hybride", "Hybrid"},
        habitability = { "High", "Elevée", "Hohe"},
        description = {
          [[Symeon is an ice planet mysteriously split at the equator by a band of solid desert. Exactly how this phenomenon is possible is unclear but some sort of weather anomaly may be responsible. The Arkship geological survey reports a fairly diverse mix of flat-lands alongside mountainous formations.]],
          [[Symeon est une planète de glace mystérieusement séparée à l'équateur par une bande de désert solide. On ne sait pas exactement comment ce phénomène est possible, mais une sorte d'anomalie météorologique pourrait en être responsable. L'étude géologique de l'Arche rapporte un mélange assez diversifié de terres plates et de formations montagneuses.]],
          [[Symeon ist ein Eisplanet, der auf mysteriöse Weise am Äquator durch ein Band aus fester Wüste gespalten ist. Wie genau dieses Phänomen möglich ist, ist unklar, aber eine Art Wetteranomalie könnte dafür verantwortlich sein. Die geologische Untersuchung des Archenschiffes berichtet von einer ziemlich vielfältigen Mischung aus Flachland und Gebirgsformationen.]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/symeon.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 0,
        positionInSystem = 11,
        satellites = nil,
        center = { 14165536.00, -85634464.00, -934464.00 },
        gravity = 3.8465,
        radius = 49050.00,
        atmosphereThickness = 6200.00,
        atmosphereRadius = 55200.00,
        GM = 9254303966.25,
        surfaceArea = 30233462784,
        surfaceAverageAltitude = 39,
        surfaceMaxAltitude = 450,
        surfaceMinAltitude = 126,
        ores = {
          {"Bauxite","Bauxite","Bauxit"},
          {"Garnierite","Garniérite","Garnierit"},
          {"Chromite","Chromite","Chromit"},
          {"Cobaltite","Cobaltite","Cobaltit"},
          {"Vanadinite","Vanadinite","Vanadinit"}
        },
        territories = 38882
      },
      [120] = {
        id = 120,
        name = { "Ion", "Ion", "Ion"},
        type = { "Planet", "Planète", "Planet"},
        biosphere = { "Ice", "Glace", "Eis"},
        classification = { "Hypopsychroplanet", "Hypopsychroplanète", "Hypopsychroplanet"},
        habitability = { "Average", "Moyenne", "Mittlere "},
        description = {
          [[Ion is nothing more than an oversized ice cube frozen through and through. It is a largely inhospitable planet due to its extremely low temperatures. The Arkship geological survey reports extremely rough mountainous terrain with little habitable land.]],
          [[Ion n'est rien de plus qu'un glaçon surdimensionné gelé de part en part. C'est une planète largement inhospitalière en raison de ses températures extrêmement basses. L'étude géologique de l'Arche rapporte un terrain montagneux extrêmement accidenté avec peu de terres habitables.]],
          [[Ion ist nichts weiter als ein überdimensionaler Eiswürfel, der durch und durch gefroren ist. Aufgrund seiner extrem niedrigen Temperaturen ist er ein weitgehend unwirtlicher Planet. Die geologische Untersuchung des Archenschiffes berichtet von extrem rauem, gebirgigem Gelände mit wenig bewohnbarem Land.]]
        },
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/ion.png",
        hasAtmosphere = true,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 0,
        positionInSystem = 12,
        satellites = { 121, 122},
        center = { 2865536.00, -99034464.00, -934464.00 },
        gravity = 3.5325,
        radius = 44950.00,
        atmosphereThickness = 9310.00,
        atmosphereRadius = 54260.00,
        GM = 7137425081.25,
        surfaceArea = 25390383104,
        surfaceAverageAltitude = 500,
        surfaceMaxAltitude = 1300,
        surfaceMinAltitude = 250,
        ores = {
          {"Acanthite","Acanthite","Akanthit"},
          {"Coal","Charbon","Kohle"},
          {"Limestone","Calcaire","Kalkstein"},
          {"Cryolite","Cryolite","Kryolith"},
          {"Rhodonite","Rhodonite","Rhodonit"}
        },
        territories = 32672
      },
      [121] = {
        id = 121,
        name = {"Ion Moon 1","Ion Lune 1","Ion Mond 1"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 120,
        positionInSystem = 1,
        satellites = nil,
        center = { 2472917.90, -99133746.27, -1133581.06 },
        gravity = 0.8635,
        radius = 11000.00,
        atmosphereThickness = 0,
        atmosphereRadius = 11000.00,
        GM = 104483500.00,
        surfaceArea = 1520530944,
        surfaceAverageAltitude = 100,
        surfaceMaxAltitude = 200,
        surfaceMinAltitude = 3,
        ores = {
          {"Natron","Natron","Soda"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Garnierite","Garniérite","Garnierit"},
          {"Columbite","Columbite","Columbit"}
        },
        territories = 1922
      },
      [122] = {
        id = 122,
        name = {"Ion Moon 2","Ion Lune 2","Ion Mond 2"},
        type = { "Moon", "Lune", "Mond"},
        biosphere = nil,
        classification = nil,
        habitability = nil,
        description = nil,
        iconPath = "gui/hud/dashboard_panel/sub_panels/maps/img/planets/moon_generic.png",
        hasAtmosphere = false,
        isSanctuary = false,
        isInSafeZone = false,
        systemId = 120,
        positionInSystem = 2,
        satellites = nil,
        center = { 2995424.17, -99275008.73, -1378482.03 },
        gravity = 1.1775,
        radius = 15000.00,
        atmosphereThickness = 0,
        atmosphereRadius = 15000.00,
        GM = 264937500.00,
        surfaceArea = 2827433472,
        surfaceAverageAltitude = -1900,
        surfaceMaxAltitude = -1400,
        surfaceMinAltitude = -2100,
        ores = {
          {"Malachite","Malachite","Malachit"},
          {"Chromite","Chromite","Chromit"},
          {"Bauxite","Bauxite","Bauxit"},
          {"Rhodonite","Rhodonite","Rhodonit"}
        },
        territories = 3632
      }
    }
  }