Criteria     = require("input/Criteria")
Vec3         = require("math/Vec3")
Task         = require("system/Task")
Point        = require("flight/route/Point")
PointOptions = require("flight/route/PointOptions")
Stopwatch    = require("system/Stopwatch")
Waypoint     = require("flight/Waypoint")
Plane        = require("math/Plane")
