name: Tests

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Git config
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install tools
      run: |
        set -e -o pipefail
        ./external/du-unit-testing/install_tools.sh
    - name: Run CI Tests
      run: |
        make test
    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          out/release/*

