name: Tests

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.REPO_TOKEN }}
    - name: Install tools
      run: |
        set -e -o pipefail
        ./external/du-libs/external/du-unit-testing/install_tools.sh
        ./install_tools.sh
    - name: Run CI Tests
      run: |
        make release-ci
    - name: Build PDF
      runs-on: ubuntu-latest
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: Manual.md
          output_dir: pdfs
          build_html: false
          table_of_contents: true
   - name: Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          out/release/**
          pdfs/**
        fail_on_unmatched_files: true
      if: startsWith(github.ref, 'refs/tags/')
